spring:
    datasource:
        url: jdbc:mysql://localhost:3306/aodb?useUnicode=true&characterEncoding=utf8
        username: dev
        password: devdev
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        database : MYSQL
        show-sql : true
        hibernate:
          ddl-auto : update
        properties:
          hibernate:
            dialect : org.hibernate.dialect.MySQL5Dialect
    kafka:
        bootstrap-servers: 127.0.0.1:9092,127.0.0.1:9093,127.0.0.1:9094
        
        producer:
           retries: 3
           batch-size: 35556
           key-serializer: org.apache.kafka.common.serialization.StringSerializer
           value-serializer: org.apache.kafka.common.serialization.StringSerializer

    